AttributesInMVC/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttributesInMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STUDENTDBEntities : DbContext
    {
        public STUDENTDBEntities()
            : base("name=STUDENTDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STUDENT> STUDENTs { get; set; }
    }
}

AttributesInMVC/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\lenovo\source\ASP .NET\AttributesInMVC\AttributesInMVC\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

AttributesInMVC/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

AttributesInMVC/Models/STUDENT.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttributesInMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    //attributes in MVC
    //attributes are indicated by square brackets over class, methods, properties
  
    public class STUDENT       
    {
        [DisplayName("student name")]   //used as label to display on webpage
        [UIHint("open in new window")]   //specifies template use to display data field
        public string name { get; set; }
        [DisplayName("student age")]   //used as label to display on webpage
        [DataType(DataType.Text)]   // to set the type of data allowed in this property
        public int age { get; set; }
        [DisplayFormat(NullDisplayText ="gender not specified")]
        [DisplayName("student gender")]
        public string gender { get; set; }
        [HiddenInput(DisplayValue =false)]  //id should be hidden and not displayed on web page
        public int id { get; set; }
    }
   
}

AttributesInMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AttributesInMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AttributesInMVC/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AttributesInMVC.Models;

namespace AttributesInMVC.Controllers
{
    //before starting refer STUDENT.cs because it has attributes
    public class StudentController : Controller
    {
        STUDENTDBEntities db = new STUDENTDBEntities();
        public ActionResult Index()
        {
            var x = db.STUDENTs.ToList();       //list of students fetched from database ->STUDENT model
            return View(x);
        }

        [HttpGet]
        public ActionResult Details(int studentid)
        {
            var y = db.STUDENTs.FirstOrDefault(x => x.id == studentid);
            return View(y);
        }
    }
}

AttributesInMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AttributesInMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AttributesInMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AttributesInMVC/Views/Student/Details.cshtml
@model AttributesInMVC.Models.STUDENT

@{
    ViewBag.title = "student details";

}


<!--<dl>is for description list , it is used with <dt> and <dd> tag-->
<!--dt tag is for description list followed by <dd> tag i.e. description item-->
<table border="2px solid black" class="center-block">
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.name);
        </td>
        <td>
            @Html.DisplayFor(model => model.name);
        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.age);
        </td>
        <td>
            @Html.DisplayFor(model => model.age);
        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.gender);
        </td>
        <td>
            @Html.DisplayFor(model => model.gender);
        </td>

    </tr>

</table>
@Html.ActionLink("back", "Index", "Student")    
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    th, td {
        padding: 10px;
    }

    .center-block {
        margin-left: auto;
        margin-right: auto;
    }
</style>

AttributesInMVC/Views/Student/Index.cshtml
@model  IEnumerable<AttributesInMVC.Models.STUDENT>
<!--Ienumerable due to list of students given in Index method-->
@{ 
    ViewBag.title = "student list";
}
<html>
<body >
    <h2 class="my">list of students</h2>
    <table border="2px solid black" class="center-block">
        <tr>
            <!--never display id-->
            <td>
                @Html.DisplayNameFor(model => model.name);
            </td>
            <td>
                @Html.DisplayNameFor(model => model.age);
            </td>
            <td>
                @Html.DisplayNameFor(model => model.gender);
            </td>

        </tr>
        @foreach (var i in Model)   //to display mode
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelitem => i.name)  <!--displayfor=to display model-->

                </td>
                <td>
                    @Html.DisplayFor(modelitem => i.age)  <!--displayfor=to display model-->

                </td>
                <td>
                    @Html.DisplayFor(modelitem => i.gender)  <!--displayfor=to display model-->

                </td>
            <td>
                @Html.ActionLink("Student Details", "Details", "Student", new { studentid = i.id }, null)
            </td>
                </tr>
        }
    </table>
    <style>
        body {
            background-color: antiquewhite;
           
        }
       .center-block{
           margin-left:auto;
           margin-right:auto;
       }
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
        th, td {
            padding: 10px;
        }
         .my{
            text-align:center;
            font-size:x-large;
        }
        
    </style>
</body>
</html>